# environment variables
environment:
  installres: ''

install:
  - ps: Install-Module Pester -Force
  - ps: Install-Module PSScriptAnalyzer -Force

build: false

test_script:
  - ps: $env:installres = .\StartUpdate.ps1; .\TestPackages.ps1
  - ps: $env:installres 