os: WMF 5

skip_commits:
  message: /updated (readme|doc).*|update (readme|doc).*s/

build: false

test_script:
  - ps: .\Update.ps1

notifications:
- provider: Email
  to:
  - aartemjevas@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false