install:
  - ps: Install-Module Pester -Force
  - ps: Install-Module PSScriptAnalyzer -Force

build: false

test_script:
  - ps: . .\StartUpdate.ps1
  - ps: . .\TestPackages.ps1
  - ps: if (!([string]::IsNullOrEmpty($testRes))) {$testRes; Add-AppveyorMessage "$($testRes | ConvertTo-Html -Fragment )"}

  
notifications:
- provider: Email
  to:
  - aartemjevas@gmail.com
  subject: 'chocofeed'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true