# environment variables
environment:
  installres: ''

install:
  - ps: Install-Module Pester -Force
  - ps: Install-Module PSScriptAnalyzer -Force

build: false

test_script:
  - ps: .\StartUpdate.ps1; .\TestPackages.ps1

notifications:

  # Email
  - provider: Email
    to:
      - aartemjevas@gmail.com
    subject: 'chocofeed build'                  # optional
    message: "{{installres}}"    # optional
    on_build_status_changed: true