# environment variables
environment:
  installres: ''

install:
  - ps: Install-Module Pester -Force
  - ps: Install-Module PSScriptAnalyzer -Force

build: false

test_script:
  - ps: .\StartUpdate.ps1; .\TestPackages.ps1

  
notifications:
- provider: Email
  to:
  - aartemjevas@gmail.com
  subject: 'chocofeed'
  message: "{{installres}}"
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true